export const FETCH_COURSES = "FETCH_COURSES";
export const SET_LIST_STATUS = "SET_LIST_STATUS";
export const ADD_NEW_COURSE = "ADD_NEW_COURSE";
export const UPDATE_COURSE = "UPDATE_COURSE";
export const DELETE_COURSE = "DELETE_COURSE";
export const FETCH_COURSE_DETAIL = "FETCH_COURSE_DETAIL";