export const FETCH_CREDENTIALS = "FETCH_CREDENTIALS";
export const FETCH_USER_LIST = "FETCH_USER_LIST";
export const ADD_NEW_USER = "ADD_NEW_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const USER_DETAIL = "USER_DETAIL";

//
export const SET_REGISTER_USER_LIST = "SET_REGISTER_USER_LIST";
export const SET_UNREGISTER_USER_LIST = "SET_UNREGISTER_USER_LIST";
export const SET_WAITING_LIST = "SET_WAITING_LIST";
//
export const REGISTER_USER = "REGISTER_USER";
export const UN_REGISTER_USER = "UN_REGISTER_USER";
